export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
// export const BUY_TO_CART = "BUY_TO_CART"
export const EMPTY_CART="EMPTY_CART"

export const PRODUCT_LIST="PRODUCT_LIST"
// export const PRODUCT_BUY="PRODUCT_BUY"

export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
// export const SET_PRODUCT_BUY="SET_PRODUCT_BUY"

export const SEARCH_PRODUCT="SEARCH_PRODUCT"
// export const PAGENATION_PRODUCT= "PAGENATION_PRODUCT"